import { Exhibit, Rank } from './types';

export const EXHIBITS: Exhibit[] = [
  // EASY - TEXT
  {
    id: 'e1',
    type: 'text',
    origin: 'human',
    content: "The woods are lovely, dark and deep, But I have promises to keep, And miles to go before I sleep, And miles to go before I sleep.",
    headline: "Stopping by Woods on a Snowy Evening",
    deskNote: "A classic poem by Robert Frost, published in 1923.",
    source: "Robert Frost, New Hampshire (1923)",
    hint: "The repetition of the final line is a deliberate poetic device, not a machine error.",
    difficulty: 'Easy'
  },
  {
    id: 'e2',
    type: 'text',
    origin: 'ai',
    content: "The algorithm processed the data with high efficiency. The output was a series of numbers that represented the probability of success. The system was optimized for performance and accuracy.",
    headline: "Technical Report Fragment",
    deskNote: "A generic technical description generated by a language model.",
    source: "AI Model GPT-3.5 (2023)",
    hint: "The prose is repetitive and lacks the nuance of a human technical writer.",
    difficulty: 'Easy'
  },
  // EASY - IMAGE
  {
    id: 'e3',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/vintage-news/800/600",
    headline: "Street Scene, New York",
    deskNote: "A black and white photograph from the early 20th century.",
    source: "Library of Congress Archive",
    hint: "Notice the authentic grain and the natural imperfections of the film.",
    difficulty: 'Easy'
  },
  {
    id: 'e4',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-glitch/800/600?blur=1",
    headline: "Cyberpunk Cityscape",
    deskNote: "A highly saturated, slightly distorted digital landscape.",
    source: "Stable Diffusion v1.5",
    hint: "The lighting is physically impossible and the edges are too sharp.",
    difficulty: 'Easy'
  },
  // MEDIUM - TEXT
  {
    id: 'm1',
    type: 'text',
    origin: 'human',
    content: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    headline: "Pride and Prejudice",
    deskNote: "The opening sentence of Jane Austen's famous novel.",
    source: "Jane Austen (1813)",
    hint: "The wit and social commentary are hallmarks of Austen's style.",
    difficulty: 'Medium'
  },
  {
    id: 'm2',
    type: 'text',
    origin: 'ai',
    content: "The sun dipped below the horizon, casting long shadows across the silent valley. A lone wolf howled in the distance, its cry echoing through the ancient trees. Nature was at peace.",
    headline: "Atmospheric Prose",
    deskNote: "A descriptive passage generated to mimic classic literature.",
    source: "Claude 3.5 Sonnet",
    hint: "The imagery is somewhat cliché and the rhythm is very predictable.",
    difficulty: 'Medium'
  },
  // MEDIUM - IMAGE
  {
    id: 'm3',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/nature-real/800/600",
    headline: "Alpine Meadow",
    deskNote: "A high-resolution photograph of a mountain landscape.",
    source: "National Geographic Contributor",
    hint: "The complex textures of the grass and rocks show real-world entropy.",
    difficulty: 'Medium'
  },
  {
    id: 'm4',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-portrait/800/600",
    headline: "Portrait of a Young Woman",
    deskNote: "A photorealistic portrait generated by an AI model.",
    source: "Midjourney v6",
    hint: "Look closely at the hair strands and the reflection in the eyes.",
    difficulty: 'Medium'
  },
  // HARD - TEXT
  {
    id: 'h1',
    type: 'text',
    origin: 'human',
    content: "The phenomenology of spirit is the science of the experience of consciousness. It is the movement of the concept from its abstract form to its concrete reality.",
    headline: "Philosophical Treatise",
    deskNote: "A dense passage from a 19th-century philosophical text.",
    source: "G.W.F. Hegel (1807)",
    hint: "The complexity of the thought process is difficult for current AI to sustain.",
    difficulty: 'Hard'
  },
  {
    id: 'h2',
    type: 'text',
    origin: 'ai',
    content: "The ontological status of the object is determined by its relationship to the subject. In the absence of a perceiving mind, the object exists only as a potentiality within the field of being.",
    headline: "Modern Metaphysics",
    deskNote: "An AI-generated passage attempting to sound like deep philosophy.",
    source: "GPT-4o",
    hint: "It uses big words but the underlying logic is slightly circular.",
    difficulty: 'Hard'
  },
  // HARD - IMAGE
  {
    id: 'h3',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/abstract-art/800/600",
    headline: "Untitled Abstract",
    deskNote: "A contemporary painting with complex layering and texture.",
    source: "Modern Art Museum",
    hint: "The physical brushstrokes and the way the paint interacts are real.",
    difficulty: 'Hard'
  },
  {
    id: 'h4',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-abstract/800/600",
    headline: "Fractal Dream",
    deskNote: "An abstract image generated using complex mathematical prompts.",
    source: "DALL-E 3",
    hint: "The patterns are mathematically perfect in a way human hands rarely achieve.",
    difficulty: 'Hard'
  }
];

export const RANKS: Rank[] = [
  { title: "The Apprentice", description: "You're just starting your investigation. The machine still fools you often.", minScore: 0 },
  { title: "The Fact Checker", description: "You have a decent eye for detail, but some sophisticated fakes get through.", minScore: 500 },
  { title: "The Senior Editor", description: "Your instincts are sharp. You can spot most manufactured culture with ease.", minScore: 1000 },
  { title: "The Bureau Chief", description: "Nothing escapes your scrutiny. You are a master of the pre-AI truth.", minScore: 1500 }
];
