import { Exhibit, Rank } from './types';

export const EXHIBITS: Exhibit[] = [
  // EASY - TEXT
  {
    id: 'e1',
    type: 'text',
    origin: 'human',
    content: "The woods are lovely, dark and deep, But I have promises to keep, And miles to go before I sleep, And miles to go before I sleep.",
    headline: "Stopping by Woods on a Snowy Evening",
    deskNote: "A classic poem by Robert Frost, published in 1923.",
    source: "Robert Frost, New Hampshire (1923)",
    hint: "The repetition of the final line is a deliberate poetic device, not a machine error.",
    difficulty: 'Easy'
  },
  {
    id: 'e2',
    type: 'text',
    origin: 'ai',
    content: "The algorithm processed the data with high efficiency. The output was a series of numbers that represented the probability of success. The system was optimized for performance and accuracy.",
    headline: "Technical Report Fragment",
    deskNote: "A generic technical description generated by a language model.",
    source: "AI Model GPT-3.5 (2023)",
    hint: "The prose is repetitive and lacks the nuance of a human technical writer.",
    difficulty: 'Easy'
  },
  {
    id: 'e3',
    type: 'text',
    origin: 'human',
    content: "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.",
    headline: "Moby-Dick; or, The Whale",
    deskNote: "The famous opening of Herman Melville's 1851 novel.",
    source: "Herman Melville (1851)",
    hint: "The voice is distinctively conversational yet grand, a signature of 19th-century prose.",
    difficulty: 'Easy'
  },
  {
    id: 'e4',
    type: 'text',
    origin: 'ai',
    content: "Once upon a time, in a land far away, there lived a king and a queen who wanted a child very much. They were kind and just, and their kingdom was peaceful and happy for many years.",
    headline: "Generic Fairy Tale",
    deskNote: "A standard fairy tale opening generated by a simple prompt.",
    source: "Large Language Model",
    hint: "The phrasing is highly conventional and lacks any unique descriptive flair.",
    difficulty: 'Easy'
  },
  {
    id: 'e5',
    type: 'text',
    origin: 'human',
    content: "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.",
    headline: "The Gettysburg Address",
    deskNote: "Abraham Lincoln's historic 1863 speech.",
    source: "Abraham Lincoln (1863)",
    hint: "The rhythmic cadence and specific biblical-inflection are uniquely Lincoln's.",
    difficulty: 'Easy'
  },
  // EASY - IMAGE
  {
    id: 'e6',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/vintage-news/800/600",
    headline: "Street Scene, New York",
    deskNote: "A black and white photograph from the early 20th century.",
    source: "Library of Congress Archive",
    hint: "Notice the authentic grain and the natural imperfections of the film.",
    difficulty: 'Easy'
  },
  {
    id: 'e7',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-glitch/800/600?blur=1",
    headline: "Cyberpunk Cityscape",
    deskNote: "A highly saturated, slightly distorted digital landscape.",
    source: "Stable Diffusion v1.5",
    hint: "The lighting is physically impossible and the edges are too sharp.",
    difficulty: 'Easy'
  },
  {
    id: 'e8',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/family-1950/800/600",
    headline: "Sunday Afternoon",
    deskNote: "A candid family snapshot from the mid-1950s.",
    source: "Personal Archive Collection",
    hint: "The faded colors and slight motion blur are characteristic of period consumer cameras.",
    difficulty: 'Easy'
  },
  {
    id: 'e9',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ultra-realistic-car/800/600",
    headline: "Futuristic Vehicle Concept",
    deskNote: "A computer-generated render of a conceptual car design.",
    source: "AI Design Tool",
    hint: "The reflections on the chrome surface are too perfect and symmetrical.",
    difficulty: 'Easy'
  },
  {
    id: 'e10',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/historical-portrait/800/600",
    headline: "Portrait of a Statesman",
    deskNote: "An official photographic portrait from the late 1800s.",
    source: "National Portrait Gallery",
    hint: "The depth of field and the specific texture of the sitter's clothing feel authentic.",
    difficulty: 'Easy'
  },
  // EASY - MIXED
  {
    id: 'e11',
    type: 'text',
    origin: 'human',
    content: "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.",
    headline: "We Shall Fight on the Beaches",
    deskNote: "Winston Churchill's defiant 1940 speech to Parliament.",
    source: "Winston Churchill (1940)",
    hint: "The powerful rhetorical repetition was designed for morale-boosting during wartime.",
    difficulty: 'Easy'
  },
  {
    id: 'e12',
    type: 'text',
    origin: 'ai',
    content: "To create a recipe for chocolate cake, you first need to gather all your ingredients: flour, sugar, cocoa powder, eggs, milk, and butter. Preheat your oven to 350 degrees Fahrenheit.",
    headline: "Automated Recipe Instruction",
    deskNote: "A straightforward instruction set from an AI model.",
    source: "RecipeBot v2",
    hint: "The tone is completely utilitarian and lacks any personal narrative or culinary insight.",
    difficulty: 'Easy'
  },
  {
    id: 'e13',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/fractal-tree/800/600",
    headline: "Infinite Branches",
    deskNote: "A digital artwork exploring mathematical fractals in nature.",
    source: "Procedural Content Generator",
    hint: "The repetition of the tree's geometry is far more precise than any natural growth.",
    difficulty: 'Easy'
  },
  {
    id: 'e14',
    type: 'text',
    origin: 'human',
    content: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.",
    headline: "I Have a Dream",
    deskNote: "Dr. Martin Luther King Jr.'s 1963 landmark speech.",
    source: "Martin Luther King Jr. (1963)",
    hint: "The visionary clarity and emotional weight are iconic features of human oratory.",
    difficulty: 'Easy'
  },
  {
    id: 'e15',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/wildlife-shot/800/600",
    headline: "Lioness in the Savannah",
    deskNote: "A nature photograph taken during a wildlife expedition.",
    source: "Wilderness Photographer",
    hint: "The composition shows a spontaneous moment in nature that AI often over-stylizes.",
    difficulty: 'Easy'
  },

  // MEDIUM - TEXT
  {
    id: 'm1',
    type: 'text',
    origin: 'human',
    content: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    headline: "Pride and Prejudice",
    deskNote: "The opening sentence of Jane Austen's famous novel.",
    source: "Jane Austen (1813)",
    hint: "The wit and social commentary are hallmarks of Austen's style.",
    difficulty: 'Medium'
  },
  {
    id: 'm2',
    type: 'text',
    origin: 'ai',
    content: "The sun dipped below the horizon, casting long shadows across the silent valley. A lone wolf howled in the distance, its cry echoing through the ancient trees. Nature was at peace.",
    headline: "Atmospheric Prose",
    deskNote: "A descriptive passage generated to mimic classic literature.",
    source: "Claude 3.5 Sonnet",
    hint: "The imagery is somewhat cliché and the rhythm is very predictable.",
    difficulty: 'Medium'
  },
  {
    id: 'm3',
    type: 'text',
    origin: 'human',
    content: "The past is a foreign country: they do things differently there. When a child, you think that the world is a place where you are the center of all things.",
    headline: "The Go-Between",
    deskNote: "Opening lines from L.P. Hartley's 1953 novel.",
    source: "L.P. Hartley (1953)",
    hint: "The philosophical pivot from the metaphor to the personal memory is a sophisticated human opening.",
    difficulty: 'Medium'
  },
  {
    id: 'm4',
    type: 'text',
    origin: 'ai',
    content: "The intersection of technology and humanity is a complex landscape. As we navigate the digital age, we must strive to maintain our core values while embracing innovation.",
    headline: "Thought Leadership Blog",
    deskNote: "A corporate-style opinion piece generated by an AI model.",
    source: "ContentEngine v4",
    hint: "The language is filled with buzzwords but lacks a truly unique or controversial thesis.",
    difficulty: 'Medium'
  },
  {
    id: 'm5',
    type: 'text',
    origin: 'human',
    content: "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles.",
    headline: "Hamlet, Act III, Scene I",
    deskNote: "Shakespeare's most famous soliloquy.",
    source: "William Shakespeare (c. 1600)",
    hint: "The density of the metaphors and the existential depth are deeply human.",
    difficulty: 'Medium'
  },
  // MEDIUM - IMAGE
  {
    id: 'm6',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/nature-real/800/600",
    headline: "Alpine Meadow",
    deskNote: "A high-resolution photograph of a mountain landscape.",
    source: "National Geographic Contributor",
    hint: "The complex textures of the grass and rocks show real-world entropy.",
    difficulty: 'Medium'
  },
  {
    id: 'm7',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-portrait/800/600",
    headline: "Portrait of a Young Woman",
    deskNote: "A photorealistic portrait generated by an AI model.",
    source: "Midjourney v6",
    hint: "Look closely at the hair strands and the reflection in the eyes.",
    difficulty: 'Medium'
  },
  {
    id: 'm8',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/street-art/800/600",
    headline: "Urban Expression",
    deskNote: "A photograph of street art in an industrial district.",
    source: "Photojournalist Archive",
    hint: "The way the light hits the uneven brick surface reveals the physical world.",
    difficulty: 'Medium'
  },
  {
    id: 'm9',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/concept-architecture/800/600",
    headline: "Eco-Friendly Skyscraper",
    deskNote: "An architectural visualization of a futuristic green building.",
    source: "AI Architecture Lab",
    hint: "The greenery seems too evenly distributed and the people look slightly uncanny.",
    difficulty: 'Medium'
  },
  {
    id: 'm10',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/market-scene/800/600",
    headline: "Local Market, Marrakech",
    deskNote: "A vibrant photo of a bustling traditional market.",
    source: "Travel Photographer",
    hint: "The chaotic composition and diverse lighting sources are difficult for AI to balance naturally.",
    difficulty: 'Medium'
  },
  // MEDIUM - MIXED
  {
    id: 'm11',
    type: 'text',
    origin: 'human',
    content: "In the end, we will remember not the words of our enemies, but the silence of our friends. This realization often comes too late to save the connections we value.",
    headline: "Reflection on Civil Rights",
    deskNote: "A modified excerpt from a Martin Luther King Jr. sermon.",
    source: "Martin Luther King Jr. (1967)",
    hint: "The internal moral conviction is expressed with a rhythm that feels lived-in.",
    difficulty: 'Medium'
  },
  {
    id: 'm12',
    type: 'text',
    origin: 'ai',
    content: "The market showed significant volatility during the afternoon session. Analysts suggest that the change in interest rates was the primary driver for the sell-off in technology stocks.",
    headline: "Financial News Summary",
    deskNote: "An automated financial report based on market data.",
    source: "FinanceAI News",
    hint: "The prose is factual but entirely devoid of any unique authorial voice or perspective.",
    difficulty: 'Medium'
  },
  {
    id: 'm13',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/digital-painting/800/600",
    headline: "Sunset over a Digital Ocean",
    deskNote: "A landscape painting created entirely within a digital environment.",
    source: "AI Artist Studio",
    hint: "The gradient in the sky is mathematically perfect, lacking natural color variance.",
    difficulty: 'Medium'
  },
  {
    id: 'm14',
    type: 'text',
    origin: 'human',
    content: "I suppose that at the end of the day, all we have are our stories. The ones we tell ourselves, and the ones we tell each other to make sense of the void.",
    headline: "Fictional Narrative",
    deskNote: "A passage from a contemporary literary novel.",
    source: "Modern Author (2015)",
    hint: "The specific combination of weariness and wonder is a complex human emotion to fake.",
    difficulty: 'Medium'
  },
  {
    id: 'm15',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/macro-leaf/800/600",
    headline: "Macro Detail of an Autumn Leaf",
    deskNote: "Close-up photograph of a decaying leaf showing intricate veins.",
    source: "Scientific Illustration Archive",
    hint: "The organic irregularity and the precise way the water droplets interact with the surface are hallmarks of reality.",
    difficulty: 'Medium'
  },

  // HARD - TEXT
  {
    id: 'h1',
    type: 'text',
    origin: 'human',
    content: "The phenomenology of spirit is the science of the experience of consciousness. It is the movement of the concept from its abstract form to its concrete reality.",
    headline: "Philosophical Treatise",
    deskNote: "A dense passage from a 19th-century philosophical text.",
    source: "G.W.F. Hegel (1807)",
    hint: "The complexity of the thought process is difficult for current AI to sustain.",
    difficulty: 'Hard'
  },
  {
    id: 'h2',
    type: 'text',
    origin: 'ai',
    content: "The ontological status of the object is determined by its relationship to the subject. In the absence of a perceiving mind, the object exists only as a potentiality within the field of being.",
    headline: "Modern Metaphysics",
    deskNote: "An AI-generated passage attempting to sound like deep philosophy.",
    source: "GPT-4o",
    hint: "It uses big words but the underlying logic is slightly circular.",
    difficulty: 'Hard'
  },
  {
    id: 'h3',
    type: 'text',
    origin: 'human',
    content: "The very concept of objective truth is fading out of the world. Lies will pass into history. What is true is whatever the Party says is true, at that moment.",
    headline: "Reflections on Propaganda",
    deskNote: "An insightful passage from George Orwell's writings.",
    source: "George Orwell (1943)",
    hint: "The sharp, pointed societal critique has a weight that AI models often dilute with 'safeguarded' language.",
    difficulty: 'Hard'
  },
  {
    id: 'h4',
    type: 'text',
    origin: 'ai',
    content: "The emergent properties of complex systems often elude reductionist analysis. To truly understand the whole, we must examine the interactions rather than just the constituent parts.",
    headline: "Systems Theory Essay",
    deskNote: "A sophisticated-sounding academic passage from an AI.",
    source: "Research Assistant AI",
    hint: "While technically correct, the phrasing is extremely typical of common academic training data.",
    difficulty: 'Hard'
  },
  {
    id: 'h5',
    type: 'text',
    origin: 'human',
    content: "In the beginning was the Word, and the Word was with God, and the Word was God. He was with God in the beginning. Through him all things were made.",
    headline: "Gospel According to John",
    deskNote: "The prologue of the Fourth Gospel, King James Version.",
    source: "Biblical Text (KJV)",
    hint: "The archaic repetition and rhythmic structure are deeply rooted in historical liturgical traditions.",
    difficulty: 'Hard'
  },
  // HARD - IMAGE
  {
    id: 'h6',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/abstract-art/800/600",
    headline: "Untitled Abstract",
    deskNote: "A contemporary painting with complex layering and texture.",
    source: "Modern Art Museum",
    hint: "The physical brushstrokes and the way the paint interacts are real.",
    difficulty: 'Hard'
  },
  {
    id: 'h7',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-abstract/800/600",
    headline: "Fractal Dream",
    deskNote: "An abstract image generated using complex mathematical prompts.",
    source: "DALL-E 3",
    hint: "The patterns are mathematically perfect in a way human hands rarely achieve.",
    difficulty: 'Hard'
  },
  {
    id: 'h8',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/glitch-art-real/800/600",
    headline: "Corrupted Memory",
    deskNote: "A photograph purposefully distorted through physical hardware glitching.",
    source: "Experimental Media Artist",
    hint: "The noise shows artifacts of analog hardware decay that digital AI simulates poorly.",
    difficulty: 'Hard'
  },
  {
    id: 'h9',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/synthetic-humanoid/800/600",
    headline: "The First Post-Human",
    deskNote: "A conceptual portrait showing a fusion of flesh and machinery.",
    source: "Advanced AI Imaging",
    hint: "The integration of textures is technically seamless but anatomically slightly skewed.",
    difficulty: 'Hard'
  },
  {
    id: 'h10',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/deep-sea/800/600",
    headline: "Abyssal Discovery",
    deskNote: "A grainy, low-light photo from a deep-sea submersible. ",
    source: "Oceanographic Expedition",
    hint: "The specific way light scatters in high-pressure seawater is incredibly difficult to fake.",
    difficulty: 'Hard'
  },
  // HARD - MIXED
  {
    id: 'h11',
    type: 'text',
    origin: 'human',
    content: "The owl of Minerva spreads its wings only with the falling of the dusk. This means that philosophy only begins to understand a culture as that culture begins to fade.",
    headline: "Philosophy of Right",
    deskNote: "A famous metaphor from G.W.F. Hegel.",
    source: "G.W.F. Hegel (1821)",
    hint: "The metaphor encapsulates a highly specific historical and philosophical worldview.",
    difficulty: 'Hard'
  },
  {
    id: 'h12',
    type: 'text',
    origin: 'ai',
    content: "The paradigm shift towards decentralization represents a fundamental restructuring of global power dynamics. This evolution is driven by the immutable nature of cryptographic protocols.",
    headline: "Crypto-Economic Manifesto",
    deskNote: "A whitepaper-style passage synthesized by AI.",
    source: "PolicyBot 9000",
    hint: "The language is extremely dense with jargon but relies heavily on current online manifestos.",
    difficulty: 'Hard'
  },
  {
    id: 'h13',
    type: 'image',
    origin: 'ai',
    content: "https://picsum.photos/seed/ai-surrealism/800/600",
    headline: "The Melting Clockwork",
    deskNote: "A surrealist piece inspired by Dali, generated by a deep learning model.",
    source: "Generative Art Collective",
    hint: "The 'surrealism' feels like a database lookup of motifs rather than a cohesive subconscious vision.",
    difficulty: 'Hard'
  },
  {
    id: 'h14',
    type: 'text',
    origin: 'human',
    content: "What is important is to spread light; to let each person feel that they are part of a larger story that did not begin with them and will not end with them.",
    headline: "Humanist Reflection",
    deskNote: "A passage from a diary found in a historical archive.",
    source: "Anonymous Diarist (c. 1910)",
    hint: "The quiet, personal sincerity of the 20th-century humanist tradition is hard to replicate without sounding 'inspiring'.",
    difficulty: 'Hard'
  },
  {
    id: 'h15',
    type: 'image',
    origin: 'human',
    content: "https://picsum.photos/seed/microscopic-cell/800/600",
    headline: "Cellular Mitosis",
    deskNote: "A photomicrograph showing cells in the process of division.",
    source: "Biomedical Imaging Lab",
    hint: "The internal biological complexity and the 'messy' reality of life are the best clues.",
    difficulty: 'Hard'
  }
];

export const RANKS: Rank[] = [
  { title: "The Apprentice", description: "You're just starting your investigation. The machine still fools you often.", minScore: 0 },
  { title: "The Fact Checker", description: "You have a decent eye for detail, but some sophisticated fakes get through.", minScore: 500 },
  { title: "The Senior Editor", description: "Your instincts are sharp. You can spot most manufactured culture with ease.", minScore: 1000 },
  { title: "The Bureau Chief", description: "Nothing escapes your scrutiny. You are a master of the pre-AI truth.", minScore: 1500 }
];
